# Generated by Django 6.0 on 2025-12-06 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
