# Generated by Django 6.0 on 2025-12-06 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(max_length=36, validators=[django.core.validators.MinLengthValidator(36)]),
        ),
    ]
